# Generated by Django 5.0 on 2024-02-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_pasted',
            new_name='date_posted',
        ),
    ]
